
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */


public  class Main : LayerWidget
{
    public void initialize() {
        base.initialize();
        set_size_request_override(px("250mm"), px("180mm"));
        add(CanvasWidget.for_colors(Color.instance("#ff8c00"), Color.instance("black")));
        add(LabelWidget.for_string("UST").set_font(Theme.font().modify("80mm bold color=blue outline color=black")));
    }

    }
